import React, { Component } from "react";

export default class IngredientList extends Component {
  constructor() {
    super();
    this.state = {
      ingIndex: 0,
      ingredients: [
        "7-Yottabyte Storage Component",
        "Acidic Remains",
        "Accursed Effigy",
        "Active Fireball",
        "Adamastor's Faceplate",
        "Acid Magma",
        "Adventurer's Diary",
        "Agullo Beak",
        "Aged Tome",
        "Alga",
        "Algae Mat",
        "Alnamar Meat",
        "Altered Ash",
        "Ancient Coins",
        "Ancient Currency",
        "Ancient Metal",
        "Ancient Moss",
        "Angelic Gem",
        "Antique Metal",
        "Ancient Heart",
        "Apple",
        "Aqua Vitae",
        "Aquatic Beauty",
        "Ashen Hide",
        "Arcane Anomaly",
        "Archaic Medallion",
        "Ball of Slime",
        "Bandit Rations",
        "Bat Ear",
        "Bamboo",
        "Bat Heart",
        "Beak of the Nivlan Beauty",
        "Beef Tongue",
        "Beastial Viscera",
        "Black Steel",
        "Black Hole",
        "Black Sulphur",
        "Blaze Powder",
        "Blessed Heart",
        "Blazing Fireball",
        "Blighted Skull",
        "Blood of the Nivlan Beauty",
        "Bloodstained Remains",
        "Bloodweb",
        "Boar Meat",
        "Bob's Tear",
        "Bone Ash",
        "Borange Fluff",
        "Bone Meal",
        "Bottled Decay",
        "Bottled Fairy",
        "Braveheart",
        "Broken Antic Bead",
        "Broken Pick",
        "Broken Dagger",
        "Broken Steel Blade",
        "Broken Helmet",
        "Broken Steel Hook",
        "Brown Mushroom",
        "Bug Parts",
        "Burning Soul",
        "Burnt Skull",
        "Calcified Ligament",
        "Calmed Thunder",
        "Captain's Glass",
        "Cat Food",
        "Carapace Fragment",
        "Cat Tail",
        "Cataratite",
        "Chain Loop",
        "Charred Carapace",
        "Chipped Quartz",
        "Charred Bone",
        "Chitin Plate",
        "Coagulated Clot",
        "Coastal Sand",
        "Coastal Shell",
        "Condor Feather",
        "Colossus' Shard",
        "Congealed Slime",
        "Condensed Darkness",
        "Conscription Letter",
        "Corbys Innards",
        "Contorted Stone",
        "Corn Husk",
        "Corrupted Fragment",
        "Corrupted Ichor",
        "Corruption Shard",
        "Coyote Fang",
        "Cracked Geode",
        "Cortrich Eggs",
        "Crawler Eye",
        "Cracked Skin",
        "Crawler Sludge",
        "Crawler Web",
        "Crumbling Skull",
        "Crystal Dust",
        "Crumbly Rock",
        "Crystalline Growth",
        "Crystallized Organ",
        "Cursed Ashes",
        "Cursed Venom Sac",
        "Acidic Blood",
        "Cursed Wings",
        "Cyclops Eye",
        "Acidic Solution",
        "Dark Iris",
        "Dead Bee",
        "Dead Naval Shard",
        "Decaying Skin",
        "Decaying Heart",
        "Decaying Arteries",
        "Defiled Luxroot",
        "Deep Ice Core",
        "Dense Void Hole Chunk",
        "Defishious",
        "Demonic Blood",
        "Demonic Ashes",
        "Desert Fossil",
        "Depreciating Flesh",
        "Depth's Gem",
        "Doom Stone",
        "Dragonling Egg",
        "Dragon Aura",
        "Dragonling Scale",
        "Dried Gill",
        "Dried Kelp",
        "Drained Bone",
        "Durable Skin",
        "Dry Bone",
        "Egg",
        "Earthly Aura",
        "Dry Seeds",
        "Electroplasm",
        "Elephant Toenail",
        "Elemental Crystal",
        "Elephelk Trunk",
        "Enchanted Chain Link",
        "Energetic Aura",
        "Engored Oculus",
        "Engraved Tablet",
        "Enhanced Behaviour Microchip",
        "Empty Casings",
        "Enhanced Dynamics Microchip",
        "Enhanced Pathfinding Microchip",
        "Enhanced Physics Microchip",
        "Enhanced Post-Processing Microchip",
        "Essence Of Dusk",
        "Eternal Flame",
        "Expelled Shrapnel",
        "Draconic Bone Marrow",
        "Eye of The Beast",
        "Fairy Powder",
        "Fairy Dust",
        "Farcor's Trust",
        "Fancy Pelt",
        "Fiery Aura",
        "Feather of Grace",
        "Firefly Dust",
        "Fiery Essence",
        "Fighting Stick",
        "Fish Scales",
        "Flameheart",
        "Flesh-forged Circuit",
        "Flow of Fate",
        "Fluffy Fur",
        "Flugsvamp Cap",
        "Forest Web",
        "Forgotten Pickaxe",
        "Foul Fairy Dust",
        "Forgotten Axe",
        "Foul Fluid",
        "Fresh Bone",
        "Fresh Game",
        "Fresh Water",
        "Frostbitten Flesh",
        "Fuming Lava Rock",
        "Frozen Ghostly Essence",
        "Fungi Spores",
        "Gelatinous Slime Chunk",
        "Galvanic Stone",
        "Ghostly Essence",
        "Gert Skin",
        "Ghostly Membrane",
        "Ghostly Plume",
        "Glacial Anomaly",
        "Gilded Bark",
        "Glimmering Beak",
        "Glittering Silt",
        "Gloomy Orb",
        "Glimmering Coin",
        "Glow Bulb Seeds",
        "Glowing Scales",
        "Gold",
        "Goblin Tooth",
        "Gold Bar",
        "Gold Nugget",
        "Gold Tooth",
        "Golden Avia Feather",
        "Golden Coin",
        "Gollier Iron",
        "Green Foot",
        "Gravitation Crystal",
        "Green Opal",
        "Green Scale",
        "Grey Cloud",
        "Gritty Rocks",
        "Grook Feather",
        "Gunpowder",
        "Gunkfueled Core",
        "Gylia Essence",
        "Haleva Plant",
        "Hardened Magma",
        "Haros' Broken Badge",
        "Hardened Mandible",
        "Harpy Bone",
        "Harpy Wing",
        "Herbstzeitlose",
        "Holy Powder",
        "Hellish Cinders",
        "Horse Mane",
        "Hunter's Disguise",
        "Hybrid Skin",
        "Hydrofluoric Acid",
        "Ibjub Fruit",
        "Ice Fragment",
        "Ice Sliver",
        "Icy Shard",
        "Iceberries",
        "Incremental Mapping Module",
        "Infected Mass",
        "Infused Gold",
        "Insanity Star",
        "Infernal Flesh",
        "Iridescent Elytra",
        "Ironwood Chips",
        "Ivory Tusk",
        "Jolting Geode",
        "Kaian Scroll",
        "Karl Johan Cap",
        "Kerasot Sporehead",
        "Large Lapis",
        "Larbonic Sheddings",
        "Laryngeal Flesh",
        "Large Titanium Chunk",
        "Lava Blisters",
        "Leg Eater Tooth",
        "Leafy Stalk",
        "Leather",
        "Lively Apple",
        "Leopard Blood",
        "Limestone Core",
        "Linear Accelerator",
        "Lion Heart",
        "Lion Fang",
        "Lithoflesh",
        "Lizard Scale",
        "Lizard Tail",
        "Lost Spirit",
        "Lost Talisman",
        "Lockpicking Kit",
        "Lucky Rabbit's Foot",
        "Lucky Spider Egg",
        "Lunar Charm",
        "Luminescent Ink",
        "Lunar Chunk",
        "Lunar Dust",
        "Lunar Shard",
        "Luu Luu Vertebrae",
        "Luxic Plasma",
        "Luxroot Cuttings",
        "Magic Feather",
        "Luxurious Silk",
        "Magmatic Skin",
        "Mahogany Heartwood",
        "Maroferrous",
        "Major's Badge",
        "Mangled Soul",
        "Manis Carapace",
        "Maromagnetite",
        "Marrow Dust",
        "Marsufosa Pelt",
        "Mashed Insect",
        "Aged Medallion",
        "Mega Fern",
        "Melted Steel",
        "Metal Scraps",
        "Mineral Cinder",
        "Mixed Mineral Deposit",
        "Mixed Jewel Deposit",
        "Mixed Seeds",
        "Mooshroom Ear",
        "More-Pearlescent Jewel",
        "Munched Grass",
        "Muscle",
        "Myconid Spores",
        "Naga Tail",
        "Native Jadeite",
        "Nasty Residue",
        "Naval Stone",
        "Naval Shard",
        "Nivlan Honey",
        "Nightmare Fuel",
        "Nivlan Honeycomb",
        "Nose Ring",
        "Obelisk Core",
        "Ocea Steel",
        "Oceanic Sand",
        "Oceanic Silt",
        "Ocelot Tail",
        "Ocelot Pelt",
        "Old Bone",
        "Old Explosives",
        "Ominous Pearl",
        "Optic Fiber",
        "Optic Lens",
        "Orc Eye",
        "Orc Skin",
        "Orc Teeth",
        "Overheated Processor",
        "Overgrown Bones",
        "Owl Feather",
        "Panda King’s Crown",
        "Panda King's Crown",
        "Paralyzing Spores",
        "Pearlescent Jewel",
        "Penguin Egg",
        "Pegasus Feather",
        "Perkish Potato",
        "Phrumkin Seeds",
        "Piercing Talons",
        "Pigman Meat",
        "Pig's Blood",
        "Pig's Remains",
        "Pig's Skull",
        "Pillaged Fragment",
        "Piquant Pork Fillet",
        "Piranha Jaw",
        "Pink Wool",
        "Pirate Beard",
        "Plane of Nonexistence",
        "Plasteel Plating",
        "Plucked Feather",
        "Plutonium Waste",
        "Poison Sac",
        "Poisonous Spider Eye",
        "Poorly-Made Pouch",
        "Portal Emanation",
        "Portal Rift",
        "Popped Pustule",
        "Potato",
        "Powdery Bone",
        "Prickly Grass",
        "Pride of the Heights",
        "Primitive Delicacy",
        "Primordial Soul",
        "Pristine Claw",
        "Prized Pelt",
        "Protective Fabric",
        "Pure Quartz",
        "Purest Tear",
        "Pure Rain Stone",
        "Putrid Gunk",
        "Putrid Spores",
        "Pykrete",
        "Cleaned Saccharum",
        "Familiar Essence",
        "Royal Cake Slice",
        "Old Treasure",
        "Shattered Memory Shard",
        "Therck's Chain",
        "Vibrant Augment",
        "Weakening Catalyst",
        "Rabbit Carcass",
        "Rancid Flesh",
        "Rare Potato",
        "Rat Hair",
        "Razor-Sharp Tooth",
        "Recluse Venom Sac",
        "Red Crystal Dust",
        "Red Mercury",
        "Reinforced Leather",
        "Reptile Scales",
        "Red Mushroom",
        "Residual Spirit",
        "Resilient Stone",
        "Retinal Membrane",
        "Ritual Catalyst",
        "Rigid Fin",
        "Retinal Barbs",
        "River Clay",
        "Robot Antenna",
        "Rocky Mind",
        "Rock-Hard Beak",
        "Rose",
        "Rotten Bone",
        "Rotten Flesh",
        "Rotten Teeth",
        "Rotten Log",
        "Royal Bug’s Blood",
        "Rusty Axe Head",
        "Router's Shield",
        "Salt",
        "Salt Water",
        "Scalding Sand",
        "Sandy Bonemeal",
        "Scarab Husk",
        "Sea Salt",
        "Seagrass",
        "Seabird Egg",
        "Seabird Feather",
        "Sentient Shadow",
        "Sentient Water",
        "Serpent Tongue",
        "Serpent's Fang",
        "Severed Heart",
        "Severed Leg",
        "Sharp Claw",
        "Sharp Edge",
        "Shattered Blade",
        "Shimmering Jewel",
        "Shinesting Scorpion Tail",
        "Shiny Mineral Deposit",
        "Shiny Pebble",
        "Shorting Wire",
        "Shredded Bone",
        "Shrieker's Head",
        "Silver Feather",
        "Sky Snail Shell",
        "Skyraider Coin",
        "Slimy Skin",
        "Sludge Parasite",
        "Smokebomb",
        "Snake Eye",
        "Smooth Silt",
        "Snake Scale",
        "Snake Skin",
        "Snake Tooth",
        "Snow Clump",
        "Snow Heart",
        "Soft Green Wool",
        "Soapstone",
        "Soft Blue Wool",
        "Soft Red Wool",
        "Soft Silk",
        "Soft Sand",
        "Soft White Wool",
        "Soft Yellow Wool",
        "Soggy Stone",
        "Sought-After Ore",
        "Soul Essence",
        "Spellbound Ash",
        "Soulbound Cinders",
        "Spark of the Oasis",
        "Spider Eggs",
        "Spider Fang",
        "Spider Leg",
        "Spiked Capsule",
        "Spike Residue",
        "Split Essence",
        "Squid Brain",
        "Squid",
        "Squid Ink",
        "Stack of Coins",
        "Sticky Fern",
        "Sticky Mudball",
        "Stolen Pearls",
        "Stolen Goods",
        "Stolen Seeds",
        "Stolen Harvest",
        "Storm Horn",
        "Stonewalker Core",
        "Strange Geode",
        "Stone Plating",
        "Stretched Rawhide",
        "Strong Flesh",
        "Squid Beak",
        "Succulent Crab Meat",
        "Subsuming Darkness",
        "Sylphid Tears",
        "Tanned Flesh",
        "Sturdy Flesh",
        "Tarnished Gold Foil",
        "Tempered Core",
        "Tender Pork Fillet",
        "Tendon Clump",
        "Tenebrous Plasma",
        "Tentacle",
        "Terracotta Chunk",
        "The Grootslang's Heart",
        "Terra Steel",
        "Thick Mud",
        "Thin Quill",
        "Thick Vines",
        "Thorned Tusk",
        "Throbbing Avos Heart",
        "Torn Rawhide",
        "Titanium Chunk",
        "Torn Skin",
        "Tough Skin",
        "Tough Bone",
        "Toxic Lumps",
        "Toxic Spores",
        "Troll Hair",
        "Toxxulous Ripper’s Legs",
        "Truffle",
        "Tungsten Chunk",
        "Turtle Shell",
        "Undead Heart",
        "Unholy Spirit",
        "Unicorn Horn",
        "Unmeltable Ice",
        "Unsettling Soul",
        "Used Fireball",
        "Victim's Skull",
        "Viking Stone",
        "Urdar's Stone",
        "Vile Stone",
        "Viscous Slime",
        "Void Essence",
        "Viral Tentacle",
        "Vim Veins",
        "Voidstone Sample",
        "Volatile Matter",
        "Vortexian Event Horizon",
        "Warped Skin",
        "Waterlogged Branch",
        "Watery Aura",
        "Weathered Idol",
        "Wendigo Bone",
        "Wind Ornament",
        "Windy Aura",
        "Werewolf Tail",
        "Wolf Fang",
        "Wood Shavings",
        "Wood Snippet",
        "Wool",
        "Wood Scrap",
        "Wooly Armour",
        "Worn Memorabilia",
        "Worn Coin",
        "Wriggling Darkness",
        "Wybel Fluff",
        "Yeti Fur",
        "Zhight Coral Piece",
        "Zhight Herbal Mix",
        "Zhight Shiny Stone",
        "Zhight Weird Magic Rock",
        "Zombie Eye"
      ]
    };
  }

  handleChange = e => {
    this.setState({ ingIndex: e.target.value }, () =>
      console.log(this.state.ingIndex)
    );
  };

  render() {
    return (
      <div>
        IngredientList.js
        <select onChange={e => this.handleChange(e)} name="ingredients">
          {this.state.ingredients.map((e, i) => (
            <option value={i}>{e}</option>
          ))}
        </select>
      </div>
    );
  }
}
